apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-prod-eva
  labels:
    component: eva-whoami
  name: eva-whoami
  namespace: platform-tools
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: whoami
    nodePort: 31514
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: eva-whoami
  sessionAffinity: None
  type: LoadBalancer
